import { Activity, FollowUpTask } from '@/types/activity';

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    opportunityId: 'opp-101',
    dealTitle: 'Enterprise AI Governance Platform (Apex Global Logistics)',
    type: 'EMAIL',
    title: 'Inactivity Alert: 14 Days without response',
    description: 'System flagged deal stagnation in Solution Mapping. Champion David Vance has not responded to 3 follow-ups.',
    performedBy: 'Revenue Rescue AI',
    performedAt: '2026-09-22 09:30',
    sentiment: 'NEGATIVE',
    impactSummary: 'Risk score elevated from 52 to 84 (Critical Leakage Risk)',
    isAutomated: true,
  },
  {
    id: 'act-2',
    opportunityId: 'opp-102',
    dealTitle: 'Multi-Cloud Infrastructure Automation (FinPulse Payments)',
    type: 'PROPOSAL_VIEWED',
    title: 'Proposal viewed by Procurement Lead',
    description: 'Jonathan Drake spent 14 minutes reviewing Commercial Terms & SLA Pricing section.',
    performedBy: 'FinPulse Procurement',
    performedAt: '2026-09-21 16:45',
    sentiment: 'CAUTION',
    impactSummary: 'High engagement detected on pricing terms.',
    isAutomated: true,
  },
  {
    id: 'act-3',
    opportunityId: 'opp-103',
    dealTitle: 'Customer Data Intelligence Cloud (Meridian Health Systems)',
    type: 'NOTE',
    title: 'Legal Redlines Stalled on BAA Rider',
    description: 'Legal team noted that Deputy General Counsel Patricia Vance refuses standard liability caps.',
    performedBy: 'Chloe Dupont',
    performedAt: '2026-09-20 14:15',
    sentiment: 'NEGATIVE',
    impactSummary: 'Cycle stalled for 25 days.',
    isAutomated: false,
  },
  {
    id: 'act-4',
    opportunityId: 'opp-104',
    dealTitle: 'Real-Time Fraud Telemetry Core (Vanguard Mutual Insurance)',
    type: 'CALL',
    title: 'Sandbox Pilot Review & Architecture Approval',
    description: 'VP Claims confirmed 94/100 pilot score and green-lit sending proposal to procurement.',
    performedBy: 'Sarah Jenkins',
    performedAt: '2026-09-20 11:00',
    sentiment: 'POSITIVE',
    impactSummary: 'Deal health score increased to 88.',
    isAutomated: false,
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpTask[] = [
  {
    id: 'task-1',
    opportunityId: 'opp-101',
    dealTitle: 'Enterprise AI Governance Platform',
    company: 'Apex Global Logistics',
    arr: 240000,
    dealRiskLevel: 'CRITICAL',
    title: 'Execute Executive Sponsor Multi-Threading with CISO Elena Rostova',
    recommendedReason: '14 days champion silence; CISO evaluating competitor security stack.',
    dueDate: '2026-09-23',
    isOverdue: true,
    isCompleted: false,
    priority: 'P0_URGENT',
    suggestedActionType: 'EXECUTIVE_ESCALATION',
  },
  {
    id: 'task-2',
    opportunityId: 'opp-102',
    dealTitle: 'Multi-Cloud Infrastructure Automation',
    company: 'FinPulse Payments',
    arr: 185000,
    dealRiskLevel: 'HIGH',
    title: 'Deliver 24-Month Multi-Year Value Re-bundle to Jonathan Drake',
    recommendedReason: 'Procurement viewed pricing 16 times; counter-offer with 12% discount for 2-yr commitment.',
    dueDate: '2026-09-23',
    isOverdue: false,
    isCompleted: false,
    priority: 'P0_URGENT',
    suggestedActionType: 'EMAIL',
  },
  {
    id: 'task-3',
    opportunityId: 'opp-103',
    dealTitle: 'Customer Data Intelligence Cloud',
    company: 'Meridian Health Systems',
    arr: 320000,
    dealRiskLevel: 'HIGH',
    title: 'Schedule Legal Bridge Counsel Session for BAA Terms',
    recommendedReason: 'Legal redlines stalled > 25 days; deal risks slipping past Q3 quarter close.',
    dueDate: '2026-09-24',
    isOverdue: false,
    isCompleted: false,
    priority: 'P1_HIGH',
    suggestedActionType: 'MEETING',
  },
  {
    id: 'task-4',
    opportunityId: 'ren-201',
    dealTitle: 'CloudMatrix Technologies (Renewal $145k)',
    company: 'CloudMatrix Technologies',
    arr: 145000,
    dealRiskLevel: 'CRITICAL',
    title: 'Assign Dedicated CS Architect to Resolve 7 Jira API Tickets',
    recommendedReason: 'Contract renews in 22 days; MAU dropped 46% and P2 tickets remain unresolved.',
    dueDate: '2026-09-23',
    isOverdue: true,
    isCompleted: false,
    priority: 'P0_URGENT',
    suggestedActionType: 'EXECUTIVE_ESCALATION',
  },
];
