import { MemoryDocument } from '@/types/ai';

export const INITIAL_MEMORY_CORPUS: MemoryDocument[] = [
  {
    id: 'mem-1',
    dealId: 'opp-101',
    dealTitle: 'Enterprise AI Governance Platform',
    company: 'Apex Global Logistics',
    sourceType: 'EMAIL',
    timestamp: '2026-09-08 14:22',
    author: 'David Vance (VP IT, Apex Global Logistics)',
    content: 'Sarah, quick update from our executive committee: CFO Marcus Sterling asked to pause all new enterprise software approvals while we finalize the Q4 compliance audit. Also, CISO Elena Rostova brought up Splunk/Datadog security modules and wants 18 questions answered regarding SOC 2 Type II data boundary isolation before anything moves forward.',
    sentiment: 'CAUTION',
    tags: ['CFO Freeze', 'Security Compliance', 'Competitor Splunk', 'Audit'],
  },
  {
    id: 'mem-2',
    dealId: 'opp-101',
    dealTitle: 'Enterprise AI Governance Platform',
    company: 'Apex Global Logistics',
    sourceType: 'CALL_TRANSCRIPT',
    timestamp: '2026-09-02 11:00',
    author: 'Elena Rostova (CISO) & Sarah Jenkins (AE)',
    content: '[Elena]: "Our primary concern is model hallucination affecting compliance reporting and whether our telemetry data is used for multi-tenant retraining. If your platform cannot provide customer-managed encryption keys (CMEK) and strict tenant isolation, we cannot approve this in legal."\n[Sarah]: "We support CMEK natively on AWS KMS and GCP Cloud KMS. I will send over our SOC 2 Type II and FedRAMP equivalent security documentation."',
    sentiment: 'CAUTION',
    tags: ['CMEK', 'Tenant Isolation', 'Security Review', 'Compliance'],
  },
  {
    id: 'mem-3',
    dealId: 'opp-102',
    dealTitle: 'Multi-Cloud Infrastructure Automation',
    company: 'FinPulse Payments',
    sourceType: 'CALL_TRANSCRIPT',
    timestamp: '2026-09-13 15:30',
    author: 'Jonathan Drake (VP Procurement) & Marcus Chen (AE)',
    content: '[Jonathan]: "Marcus, we love the platform capabilities and Rachel Zane\'s engineering team gave it full technical sign-off. However, $185k/year is over our allocated Q3 budget for tooling. If you can do $140k for Year 1 or give us a 12-15% discount for a 2-year upfront commitment, I can execute the paperwork by next Friday."',
    sentiment: 'CAUTION',
    tags: ['Budget Objection', 'Discount Request', 'Multi-Year Contract', 'Procurement'],
  },
  {
    id: 'mem-4',
    dealId: 'opp-103',
    dealTitle: 'Customer Data Intelligence Cloud',
    company: 'Meridian Health Systems',
    sourceType: 'MEETING_NOTE',
    timestamp: '2026-09-11 16:00',
    author: 'Chloe Dupont (Enterprise AE)',
    content: 'Meeting with CMIO Dr. Arthur Campbell. Campbell is completely bought in and wants go-live by Nov 1 to handle open enrollment patient surges. However, Deputy General Counsel Patricia Vance has redlined our BAA indemnity section. She wants full uncapped liability on any hypothetical breach. Need our Legal team to jump on a bridge call to offer the standard $10M super-cap rider.',
    sentiment: 'CAUTION',
    tags: ['BAA Agreement', 'HIPAA Indemnity', 'Legal Redlines', 'CMIO Champion'],
  },
  {
    id: 'mem-5',
    dealId: 'ren-201',
    dealTitle: 'CloudMatrix Technologies (Renewal $145k)',
    company: 'CloudMatrix Technologies',
    sourceType: 'CALL_TRANSCRIPT',
    timestamp: '2026-09-04 10:30',
    author: 'Julian Hayes (New VP Eng) & Sarah Jenkins (CS Lead)',
    content: '[Julian]: "I took over the engineering organization 6 weeks ago. Frankly, looking at our usage dashboard, our developers haven\'t adopted the automated rescue workflows because of latency issues and 7 open tickets in Jira that haven\'t been resolved. Unless these stability issues are resolved and we get a dedicated technical account manager, we won\'t be renewing next month."',
    sentiment: 'NEGATIVE',
    tags: ['Churn Risk', 'Unresolved Tickets', 'New Leadership', 'Adoption Drop'],
  },
  {
    id: 'mem-6',
    dealId: 'opp-104',
    dealTitle: 'Real-Time Fraud Telemetry Core',
    company: 'Vanguard Mutual Insurance',
    sourceType: 'EXECUTIVE_MEMO',
    timestamp: '2026-09-20 12:00',
    author: 'Liam Gallagher (VP Claims Risk)',
    content: 'To Investment Committee: The 14-day technical sandbox pilot with Revenue Rescue AI demonstrated a 42% decrease in false positive claim investigations, projecting $2.8M in annual operational savings. Recommending approval of the $150k annual contract with immediate rollout.',
    sentiment: 'POSITIVE',
    tags: ['ROI 42%', 'Pilot Success', 'Executive Buy-in', 'High Intent'],
  },
];
