import { Opportunity } from '@/types/opportunity';

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-101',
    title: 'Enterprise AI Governance Platform',
    company: 'Apex Global Logistics',
    industry: 'Enterprise SaaS',
    arr: 240000,
    stage: 'SOLUTION_MAPPING',
    ownerName: 'Sarah Jenkins',
    ownerAvatar: 'SJ',
    riskScore: 84,
    riskLevel: 'CRITICAL',
    healthScore: 28,
    daysInStage: 23,
    inactivityDays: 14,
    expectedCloseDate: '2026-10-15',
    lastActivityDate: '2026-09-08',
    summary: 'Lead champion (VP IT) shifted priorities; cybersecurity team raised 18 compliance questions with zero response from our end for 14 days.',
    dealMemorySnippet: 'Last interaction was an email from VP IT David Vance stating CFO requested immediate freeze on non-essential cloud spend until audit completes.',
    stakeholders: [
      {
        id: 'sh-1',
        name: 'David Vance',
        title: 'VP Information Technology',
        email: 'd.vance@apexlogistics.com',
        role: 'CHAMPION',
        sentiment: 'CAUTIOUS',
        lastInteractedAt: '2026-09-08',
      },
      {
        id: 'sh-2',
        name: 'Elena Rostova',
        title: 'Chief Information Security Officer',
        email: 'e.rostova@apexlogistics.com',
        role: 'BLOCKER',
        sentiment: 'NEGATIVE',
        lastInteractedAt: '2026-09-02',
      },
      {
        id: 'sh-3',
        name: 'Marcus Sterling',
        title: 'Chief Financial Officer',
        email: 'm.sterling@apexlogistics.com',
        role: 'ECONOMIC_BUYER',
        sentiment: 'NEUTRAL',
        lastInteractedAt: '2026-08-28',
      },
    ],
    riskFactors: [
      {
        id: 'rf-1',
        category: 'INACTIVITY',
        title: '14 Days Total Silence from Champion',
        severity: 'CRITICAL',
        description: 'No outbound communication or meeting confirmed since Sept 8. Velocity fallen by 85%.',
        detectedAt: '2026-09-18',
        impactArr: 240000,
      },
      {
        id: 'rf-2',
        category: 'COMPETITIVE_THREAT',
        title: 'Competitor Mentioned in Security Audit',
        severity: 'HIGH',
        description: 'CISO Elena Rostova referenced evaluating Datadog/Splunk security add-ons instead.',
        detectedAt: '2026-09-14',
        impactArr: 240000,
      },
    ],
    recommendedPlaybooks: [
      {
        id: 'pb-1',
        title: 'Executive Sponsor Multi-Threading',
        description: 'Send our VP of Engineering to schedule a 20-min direct technical alignment session with CISO Elena Rostova.',
        type: 'EXECUTIVE_ALIGNMENT',
        estimatedRecoveryChance: 78,
        recommendedAction: 'Trigger Executive Alignment Email & Security Brief Pack',
        draftedPayload: {
          subject: 'Direct Executive Alignment: Resolving Apex Logistics SOC2 & Encryption Specs',
          body: 'Hi Elena,\n\nI understand your team is evaluating rigorous governance protocols for the AI platform. Our VP of Engineering, Marcus Chen, is available this Thursday at 2 PM to address all 18 security points directly with your team.\n\nBest regards,\nSarah Jenkins',
        },
      },
      {
        id: 'pb-2',
        title: 'Security Architecture Assurance Deck',
        description: 'Deliver pre-validated FedRAMP & SOC2 Type II compliance dossier to bypass security committee delays.',
        type: 'SECURITY_ACCELERATOR',
        estimatedRecoveryChance: 65,
        recommendedAction: 'Send Instant Security Packet to CISO',
      },
    ],
  },
  {
    id: 'opp-102',
    title: 'Multi-Cloud Infrastructure Automation',
    company: 'FinPulse Payments',
    industry: 'Fintech',
    arr: 185000,
    stage: 'EXECUTIVE_REVIEW',
    ownerName: 'Marcus Chen',
    ownerAvatar: 'MC',
    riskScore: 68,
    riskLevel: 'HIGH',
    healthScore: 42,
    daysInStage: 16,
    inactivityDays: 9,
    expectedCloseDate: '2026-09-30',
    lastActivityDate: '2026-09-13',
    summary: 'Proposal viewed 24 times across 6 stakeholders, but procurement requested 25% price reduction before contract signing.',
    dealMemorySnippet: 'CFO requested a 2-year upfront commitment discount or elimination of platform onboarding fees.',
    stakeholders: [
      {
        id: 'sh-4',
        name: 'Rachel Zane',
        title: 'Head of Infrastructure',
        email: 'r.zane@finpulse.io',
        role: 'CHAMPION',
        sentiment: 'POSITIVE',
        lastInteractedAt: '2026-09-13',
      },
      {
        id: 'sh-5',
        name: 'Jonathan Drake',
        title: 'VP Finance & Procurement',
        email: 'j.drake@finpulse.io',
        role: 'ECONOMIC_BUYER',
        sentiment: 'CAUTIOUS',
        lastInteractedAt: '2026-09-10',
      },
    ],
    riskFactors: [
      {
        id: 'rf-3',
        category: 'DISCOUNT_PRESSURE',
        title: 'Procurement Pushback on Year-1 Pricing',
        severity: 'HIGH',
        description: 'Jonathan Drake requested $45k concession to finalize before Q3 quarter close.',
        detectedAt: '2026-09-15',
        impactArr: 185000,
      },
    ],
    recommendedPlaybooks: [
      {
        id: 'pb-3',
        title: 'Value-Preserving Tier Re-bundle',
        description: 'Offer a 12% concession conditioned on a 24-month multi-year commitment and net-30 payment terms.',
        type: 'OBJECTION_REBUTTAL',
        estimatedRecoveryChance: 88,
        recommendedAction: 'Generate Multi-Year Incentive Proposal',
        draftedPayload: {
          subject: 'FinPulse Payments // 24-Month Partnership & Value Concession Framework',
          discountPercent: 12,
          body: 'Hi Jonathan & Rachel,\n\nTo help align with FinPulse Q3 budgetary milestones, we have structured an approved multi-year framework that locks in preferred volume rates with zero implementation fees.\n\nBest regards,\nMarcus Chen',
        },
      },
    ],
  },
  {
    id: 'opp-103',
    title: 'Customer Data Intelligence Cloud',
    company: 'Meridian Health Systems',
    industry: 'Healthcare',
    arr: 320000,
    stage: 'LEGAL_SECURITY',
    ownerName: 'Chloe Dupont',
    ownerAvatar: 'CD',
    riskScore: 79,
    riskLevel: 'HIGH',
    healthScore: 35,
    daysInStage: 31,
    inactivityDays: 11,
    expectedCloseDate: '2026-10-30',
    lastActivityDate: '2026-09-11',
    summary: 'Redlines stalled in Legal regarding HIPAA Business Associate Agreement (BAA) indemnification clauses.',
    dealMemorySnippet: 'General Counsel requested unlimited liability for PHI data exposure, which exceeds standard terms.',
    stakeholders: [
      {
        id: 'sh-6',
        name: 'Dr. Arthur Campbell',
        title: 'Chief Medical Information Officer',
        email: 'acampbell@meridianhealth.org',
        role: 'CHAMPION',
        sentiment: 'POSITIVE',
        lastInteractedAt: '2026-09-11',
      },
      {
        id: 'sh-7',
        name: 'Patricia Vance',
        title: 'Deputy General Counsel',
        email: 'pvance@meridianhealth.org',
        role: 'BLOCKER',
        sentiment: 'CAUTIOUS',
        lastInteractedAt: '2026-09-07',
      },
    ],
    riskFactors: [
      {
        id: 'rf-4',
        category: 'VELOCITY_DROP',
        title: 'Legal Redline Cycle Exceeds 25 Days',
        severity: 'CRITICAL',
        description: 'Standard cycle is 7 days. Risk of deal slipping into Q1 2027.',
        detectedAt: '2026-09-16',
        impactArr: 320000,
      },
    ],
    recommendedPlaybooks: [
      {
        id: 'pb-4',
        title: 'Counsel-to-Counsel Fast Track',
        description: 'Schedule a 30-min live legal bridge session between internal Legal Counsel and Patricia Vance with pre-approved BAA fallback riders.',
        type: 'CADENCE_ACCELERATOR',
        estimatedRecoveryChance: 82,
        recommendedAction: 'Schedule Legal Bridge Session',
      },
    ],
  },
  {
    id: 'opp-104',
    title: 'Real-Time Fraud Telemetry Core',
    company: 'Vanguard Mutual Insurance',
    industry: 'Insurance',
    arr: 150000,
    stage: 'PROPOSAL_OUT',
    ownerName: 'Sarah Jenkins',
    ownerAvatar: 'SJ',
    riskScore: 24,
    riskLevel: 'LOW',
    healthScore: 88,
    daysInStage: 6,
    inactivityDays: 2,
    expectedCloseDate: '2026-10-05',
    lastActivityDate: '2026-09-20',
    summary: 'High stakeholder engagement. Executive team completed technical pilot scoring 94/100 satisfaction.',
    dealMemorySnippet: 'Head of Claims confirmed our solution reduced false positives by 42% in Sandbox testing.',
    stakeholders: [
      {
        id: 'sh-8',
        name: 'Liam Gallagher',
        title: 'VP Claims Risk',
        email: 'liam.g@vanguardinsurance.com',
        role: 'CHAMPION',
        sentiment: 'POSITIVE',
        lastInteractedAt: '2026-09-20',
      },
    ],
    riskFactors: [],
    recommendedPlaybooks: [],
  },
  {
    id: 'opp-105',
    title: 'Global Compliance & Audit Suite',
    company: 'Stratos Advisory Partners',
    industry: 'Consulting',
    arr: 95000,
    stage: 'DISCOVERY',
    ownerName: 'Marcus Chen',
    ownerAvatar: 'MC',
    riskScore: 45,
    riskLevel: 'MEDIUM',
    healthScore: 65,
    daysInStage: 12,
    inactivityDays: 5,
    expectedCloseDate: '2026-11-15',
    lastActivityDate: '2026-09-17',
    summary: 'Evaluating 3 vendors. Needs clear differentiation on automated audit trail exports.',
    dealMemorySnippet: 'Managing Partner emphasized urgency to replace manual Excel workflows before year-end filing.',
    stakeholders: [
      {
        id: 'sh-9',
        name: 'Tara Simmons',
        title: 'Senior Partner',
        email: 't.simmons@stratosadvisory.com',
        role: 'CHAMPION',
        sentiment: 'NEUTRAL',
        lastInteractedAt: '2026-09-17',
      },
    ],
    riskFactors: [
      {
        id: 'rf-5',
        category: 'COMPETITIVE_THREAT',
        title: 'Vendor Bake-off with Competitor',
        severity: 'MEDIUM',
        description: 'Shortlisted alongside standard Big-4 legacy tool.',
        detectedAt: '2026-09-18',
        impactArr: 95000,
      },
    ],
    recommendedPlaybooks: [
      {
        id: 'pb-5',
        title: 'Competitive Differentiation Kit',
        description: 'Send interactive ROI & Feature comparison matrix focused on 8x faster audit generation.',
        type: 'PROPOSAL_RECALIBRATION',
        estimatedRecoveryChance: 74,
        recommendedAction: 'Send Stratos Tailored Comparison Deck',
      },
    ],
  },
  {
    id: 'opp-106',
    title: 'Autonomous Threat Hunting Node',
    company: 'CipherShield Defense',
    industry: 'Cybersecurity',
    arr: 210000,
    stage: 'CLOSED_WON',
    ownerName: 'Chloe Dupont',
    ownerAvatar: 'CD',
    riskScore: 5,
    riskLevel: 'HEALTHY',
    healthScore: 96,
    daysInStage: 4,
    inactivityDays: 1,
    expectedCloseDate: '2026-09-18',
    lastActivityDate: '2026-09-21',
    summary: 'Deal successfully executed. Onboarding kickoff scheduled for next Monday.',
    dealMemorySnippet: 'Signed 3-year agreement at $210k ARR with expansion clause for APAC division.',
    stakeholders: [],
    riskFactors: [],
    recommendedPlaybooks: [],
  },
];
