import { RenewalAccount } from '@/types/renewal';

export const INITIAL_RENEWALS: RenewalAccount[] = [
  {
    id: 'ren-201',
    accountName: 'CloudMatrix Technologies',
    contractValue: 145000,
    currentTier: 'ENTERPRISE',
    renewalDate: '2026-10-14',
    daysUntilRenewal: 22,
    healthScore: 31,
    churnRisk: 'CRITICAL',
    churnProbability: 82,
    primaryContact: {
      name: 'Julian Hayes',
      email: 'jhayes@cloudmatrix.com',
      role: 'VP Engineering',
    },
    accountManager: 'Sarah Jenkins',
    npsScore: 4,
    usageTrend: 'DECLINING_SHARP',
    unresolvedTicketsCount: 7,
    executiveSponsorActive: false,
    rescueActionRecommended: 'Dispatch Executive VP Support & Offer Dedicated CS Architect',
    churnRiskDrivers: [
      'Active monthly active users dropped 46% over past 60 days',
      'Original champion (VP Eng) departed 3 months ago; new management unengaged',
      '7 unresolved Priority-2 API performance tickets in Jira',
    ],
    status: 'PENDING_RENEWAL',
  },
  {
    id: 'ren-202',
    accountName: 'Optima Health Solutions',
    contractValue: 98000,
    currentTier: 'GROWTH',
    renewalDate: '2026-11-01',
    daysUntilRenewal: 40,
    healthScore: 54,
    churnRisk: 'HIGH',
    churnProbability: 64,
    primaryContact: {
      name: 'Samantha Reed',
      email: 'sreed@optimahealth.org',
      role: 'Director of Operations',
    },
    accountManager: 'Marcus Chen',
    npsScore: 6,
    usageTrend: 'FLAT',
    unresolvedTicketsCount: 3,
    executiveSponsorActive: true,
    rescueActionRecommended: 'Present Annual Business Review (ABR) with Quantified Value Metrics',
    churnRiskDrivers: [
      'Budget scrutiny from finance department looking to consolidate vendors',
      'Only 60% of contracted seat licenses currently provisioned',
    ],
    status: 'PENDING_RENEWAL',
  },
  {
    id: 'ren-203',
    accountName: 'Sovereign Capital Management',
    contractValue: 260000,
    currentTier: 'ENTERPRISE',
    renewalDate: '2026-11-28',
    daysUntilRenewal: 67,
    healthScore: 92,
    churnRisk: 'LOW',
    churnProbability: 8,
    primaryContact: {
      name: 'Christian Bale',
      email: 'cbale@sovereigncap.com',
      role: 'Chief Technology Officer',
    },
    accountManager: 'Chloe Dupont',
    npsScore: 10,
    usageTrend: 'GROWING',
    unresolvedTicketsCount: 0,
    executiveSponsorActive: true,
    rescueActionRecommended: 'Trigger 30% Expansion & Multi-Year Upsell Proposal',
    churnRiskDrivers: [],
    status: 'PENDING_RENEWAL',
  },
  {
    id: 'ren-204',
    accountName: 'Beacon Insurance Brokers',
    contractValue: 72000,
    currentTier: 'STARTER',
    renewalDate: '2026-10-05',
    daysUntilRenewal: 13,
    healthScore: 45,
    churnRisk: 'HIGH',
    churnProbability: 58,
    primaryContact: {
      name: 'Melissa Thorne',
      email: 'mthorne@beaconbroker.com',
      role: 'Operations Lead',
    },
    accountManager: 'Sarah Jenkins',
    npsScore: 5,
    usageTrend: 'DECLINING_SLOW',
    unresolvedTicketsCount: 2,
    executiveSponsorActive: false,
    rescueActionRecommended: 'Deliver 1-on-1 Admin Training Session & Lock In Renewal Promo',
    churnRiskDrivers: [
      'Customer unaware of new Q3 workflow automation features',
      '13 days remaining on contract without signed renewal order form',
    ],
    status: 'RESCUE_IN_PROGRESS',
  },
];
